version: '2'
services:
  node1:
    environment:
      - NAME=1
      - HOST=0.0.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3006:3006"
    volumes:
    - ./:/tivancoin
  node2:
    environment:      
      - HOST=0.0.0.0
      - NAME=2
      - PEERS=http://node1:3006      
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3002:3006"
    volumes:
    - ./:/tivancoin
    links:
      - node1:node1
  node3:
    environment:
      - HOST=0.0.0.0
      - NAME=3
      - PEERS=http://node2:3006      
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3003:3006"
    volumes:
    - ./:/tivancoin
    links:
      - node2:node2
